<?php

declare(strict_types=1);

/**
 * @generated Wildberries OpenAPI DTO
 */

namespace PhpSoftBox\Wildberries\Dto\Finances\Api\Finance;

use PhpSoftBox\Wildberries\Dto\WildberriesDtoInterface;
use PhpSoftBox\Wildberries\Dto\WildberriesDtoValue;

final readonly class SalesReportsDetailedRes implements WildberriesDtoInterface
{
    /**
     * @param array<string, mixed> $extra
     */
    public function __construct(
        public ?int $reportId,
        public ?string $dateFrom,
        public ?string $dateTo,
        public ?string $createDate,
        public ?string $currency,
        public ?int $reportType,
        public ?int $rrdId,
        public ?int $giId,
        public ?float $dlvPrc,
        public ?string $fixTariffDateFrom,
        public ?string $fixTariffDateTo,
        public ?string $subjectName,
        public ?int $nmId,
        public ?string $brandName,
        public ?string $vendorCode,
        public ?string $title,
        public ?string $techSize,
        public ?string $sku,
        public ?string $docTypeName,
        public ?int $quantity,
        public ?string $retailPrice,
        public ?string $retailAmount,
        public ?int $salePercent,
        public ?float $commissionPercent,
        public ?string $officeName,
        public ?string $sellerOperName,
        public ?string $orderDt,
        public ?string $saleDt,
        public ?string $rrDate,
        public ?int $shkId,
        public ?string $retailPriceWithDisc,
        public ?int $deliveryAmount,
        public ?int $returnAmount,
        public ?string $deliveryService,
        public ?string $giBoxTypeName,
        public ?float $productDiscountForReport,
        public ?string $sellerPromo,
        public ?float $spp,
        public ?float $kvwBase,
        public ?float $kvw,
        public ?float $supRatingUp,
        public ?float $isKgvpV2,
        public ?string $ppvzSalesCommission,
        public ?string $forPay,
        public ?string $ppvzReward,
        public ?string $acquiringFee,
        public ?float $acquiringPercent,
        public ?string $paymentProcessing,
        public ?string $acquiringBank,
        public ?string $vw,
        public ?string $vwNds,
        public ?string $ppvzOfficeName,
        public ?int $ppvzOfficeId,
        public ?string $ppvzSupplierName,
        public ?string $ppvzSupplierInn,
        public ?string $declarationNumber,
        public ?string $bonusTypeName,
        public ?string $stickerId,
        public ?string $country,
        public ?bool $srvDbs,
        public ?string $penalty,
        public ?string $additionalPayment,
        public ?string $rebillLogisticCost,
        public ?string $rebillLogisticOrg,
        public ?string $paidStorage,
        public ?string $deduction,
        public ?string $paidAcceptance,
        public ?int $orderId,
        public ?string $kiz,
        public ?bool $isB2b,
        public ?string $trbxId,
        public ?string $installmentCofinancingAmount,
        public ?float $wibesDiscountPercent,
        public ?string $cashbackAmount,
        public ?string $cashbackDiscount,
        public ?string $cashbackCommissionChange,
        public ?string $paymentSchedule,
        public ?string $deliveryMethod,
        public ?int $sellerPromoId,
        public ?float $sellerPromoDiscount,
        public ?int $loyaltyId,
        public ?float $loyaltyDiscount,
        public ?string $uuidPromocode,
        public ?float $salePricePromocodeDiscountPrc,
        public ?string $articleSubstitution,
        public ?float $salePriceAffiliatedDiscountPrc,
        public ?float $agencyVat,
        public ?float $salePriceWholesaleDiscountPrc,
        public ?string $b2bCustomerTin,
        public ?bool $paidWithSocialCertificate,
        public ?float $warehouseLogisticsCoeff,
        public ?string $orderUid,
        public ?string $srid,
        public array $extra = [],
    ) {
    }

    public static function fromArray(array $payload): static
    {
        return new self(
            reportId: WildberriesDtoValue::int($payload['reportId'] ?? null),
            dateFrom: WildberriesDtoValue::string($payload['dateFrom'] ?? null),
            dateTo: WildberriesDtoValue::string($payload['dateTo'] ?? null),
            createDate: WildberriesDtoValue::string($payload['createDate'] ?? null),
            currency: WildberriesDtoValue::string($payload['currency'] ?? null),
            reportType: WildberriesDtoValue::int($payload['reportType'] ?? null),
            rrdId: WildberriesDtoValue::int($payload['rrdId'] ?? null),
            giId: WildberriesDtoValue::int($payload['giId'] ?? null),
            dlvPrc: WildberriesDtoValue::float($payload['dlvPrc'] ?? null),
            fixTariffDateFrom: WildberriesDtoValue::string($payload['fixTariffDateFrom'] ?? null),
            fixTariffDateTo: WildberriesDtoValue::string($payload['fixTariffDateTo'] ?? null),
            subjectName: WildberriesDtoValue::string($payload['subjectName'] ?? null),
            nmId: WildberriesDtoValue::int($payload['nmId'] ?? null),
            brandName: WildberriesDtoValue::string($payload['brandName'] ?? null),
            vendorCode: WildberriesDtoValue::string($payload['vendorCode'] ?? null),
            title: WildberriesDtoValue::string($payload['title'] ?? null),
            techSize: WildberriesDtoValue::string($payload['techSize'] ?? null),
            sku: WildberriesDtoValue::string($payload['sku'] ?? null),
            docTypeName: WildberriesDtoValue::string($payload['docTypeName'] ?? null),
            quantity: WildberriesDtoValue::int($payload['quantity'] ?? null),
            retailPrice: WildberriesDtoValue::string($payload['retailPrice'] ?? null),
            retailAmount: WildberriesDtoValue::string($payload['retailAmount'] ?? null),
            salePercent: WildberriesDtoValue::int($payload['salePercent'] ?? null),
            commissionPercent: WildberriesDtoValue::float($payload['commissionPercent'] ?? null),
            officeName: WildberriesDtoValue::string($payload['officeName'] ?? null),
            sellerOperName: WildberriesDtoValue::string($payload['sellerOperName'] ?? null),
            orderDt: WildberriesDtoValue::string($payload['orderDt'] ?? null),
            saleDt: WildberriesDtoValue::string($payload['saleDt'] ?? null),
            rrDate: WildberriesDtoValue::string($payload['rrDate'] ?? null),
            shkId: WildberriesDtoValue::int($payload['shkId'] ?? null),
            retailPriceWithDisc: WildberriesDtoValue::string($payload['retailPriceWithDisc'] ?? null),
            deliveryAmount: WildberriesDtoValue::int($payload['deliveryAmount'] ?? null),
            returnAmount: WildberriesDtoValue::int($payload['returnAmount'] ?? null),
            deliveryService: WildberriesDtoValue::string($payload['deliveryService'] ?? null),
            giBoxTypeName: WildberriesDtoValue::string($payload['giBoxTypeName'] ?? null),
            productDiscountForReport: WildberriesDtoValue::float($payload['productDiscountForReport'] ?? null),
            sellerPromo: WildberriesDtoValue::string($payload['sellerPromo'] ?? null),
            spp: WildberriesDtoValue::float($payload['spp'] ?? null),
            kvwBase: WildberriesDtoValue::float($payload['kvwBase'] ?? null),
            kvw: WildberriesDtoValue::float($payload['kvw'] ?? null),
            supRatingUp: WildberriesDtoValue::float($payload['supRatingUp'] ?? null),
            isKgvpV2: WildberriesDtoValue::float($payload['isKgvpV2'] ?? null),
            ppvzSalesCommission: WildberriesDtoValue::string($payload['ppvzSalesCommission'] ?? null),
            forPay: WildberriesDtoValue::string($payload['forPay'] ?? null),
            ppvzReward: WildberriesDtoValue::string($payload['ppvzReward'] ?? null),
            acquiringFee: WildberriesDtoValue::string($payload['acquiringFee'] ?? null),
            acquiringPercent: WildberriesDtoValue::float($payload['acquiringPercent'] ?? null),
            paymentProcessing: WildberriesDtoValue::string($payload['paymentProcessing'] ?? null),
            acquiringBank: WildberriesDtoValue::string($payload['acquiringBank'] ?? null),
            vw: WildberriesDtoValue::string($payload['vw'] ?? null),
            vwNds: WildberriesDtoValue::string($payload['vwNds'] ?? null),
            ppvzOfficeName: WildberriesDtoValue::string($payload['ppvzOfficeName'] ?? null),
            ppvzOfficeId: WildberriesDtoValue::int($payload['ppvzOfficeId'] ?? null),
            ppvzSupplierName: WildberriesDtoValue::string($payload['ppvzSupplierName'] ?? null),
            ppvzSupplierInn: WildberriesDtoValue::string($payload['ppvzSupplierInn'] ?? null),
            declarationNumber: WildberriesDtoValue::string($payload['declarationNumber'] ?? null),
            bonusTypeName: WildberriesDtoValue::string($payload['bonusTypeName'] ?? null),
            stickerId: WildberriesDtoValue::string($payload['stickerId'] ?? null),
            country: WildberriesDtoValue::string($payload['country'] ?? null),
            srvDbs: WildberriesDtoValue::bool($payload['srvDbs'] ?? null),
            penalty: WildberriesDtoValue::string($payload['penalty'] ?? null),
            additionalPayment: WildberriesDtoValue::string($payload['additionalPayment'] ?? null),
            rebillLogisticCost: WildberriesDtoValue::string($payload['rebillLogisticCost'] ?? null),
            rebillLogisticOrg: WildberriesDtoValue::string($payload['rebillLogisticOrg'] ?? null),
            paidStorage: WildberriesDtoValue::string($payload['paidStorage'] ?? null),
            deduction: WildberriesDtoValue::string($payload['deduction'] ?? null),
            paidAcceptance: WildberriesDtoValue::string($payload['paidAcceptance'] ?? null),
            orderId: WildberriesDtoValue::int($payload['orderId'] ?? null),
            kiz: WildberriesDtoValue::string($payload['kiz'] ?? null),
            isB2b: WildberriesDtoValue::bool($payload['isB2b'] ?? null),
            trbxId: WildberriesDtoValue::string($payload['trbxId'] ?? null),
            installmentCofinancingAmount: WildberriesDtoValue::string($payload['installmentCofinancingAmount'] ?? null),
            wibesDiscountPercent: WildberriesDtoValue::float($payload['wibesDiscountPercent'] ?? null),
            cashbackAmount: WildberriesDtoValue::string($payload['cashbackAmount'] ?? null),
            cashbackDiscount: WildberriesDtoValue::string($payload['cashbackDiscount'] ?? null),
            cashbackCommissionChange: WildberriesDtoValue::string($payload['cashbackCommissionChange'] ?? null),
            paymentSchedule: WildberriesDtoValue::string($payload['paymentSchedule'] ?? null),
            deliveryMethod: WildberriesDtoValue::string($payload['deliveryMethod'] ?? null),
            sellerPromoId: WildberriesDtoValue::int($payload['sellerPromoId'] ?? null),
            sellerPromoDiscount: WildberriesDtoValue::float($payload['sellerPromoDiscount'] ?? null),
            loyaltyId: WildberriesDtoValue::int($payload['loyaltyId'] ?? null),
            loyaltyDiscount: WildberriesDtoValue::float($payload['loyaltyDiscount'] ?? null),
            uuidPromocode: WildberriesDtoValue::string($payload['uuidPromocode'] ?? null),
            salePricePromocodeDiscountPrc: WildberriesDtoValue::float($payload['salePricePromocodeDiscountPrc'] ?? null),
            articleSubstitution: WildberriesDtoValue::string($payload['articleSubstitution'] ?? null),
            salePriceAffiliatedDiscountPrc: WildberriesDtoValue::float($payload['salePriceAffiliatedDiscountPrc'] ?? null),
            agencyVat: WildberriesDtoValue::float($payload['agencyVat'] ?? null),
            salePriceWholesaleDiscountPrc: WildberriesDtoValue::float($payload['salePriceWholesaleDiscountPrc'] ?? null),
            b2bCustomerTin: WildberriesDtoValue::string($payload['b2bCustomerTin'] ?? null),
            paidWithSocialCertificate: WildberriesDtoValue::bool($payload['paidWithSocialCertificate'] ?? null),
            warehouseLogisticsCoeff: WildberriesDtoValue::float($payload['warehouseLogisticsCoeff'] ?? null),
            orderUid: WildberriesDtoValue::string($payload['orderUid'] ?? null),
            srid: WildberriesDtoValue::string($payload['srid'] ?? null),
            extra: WildberriesDtoValue::extra($payload, ['reportId', 'dateFrom', 'dateTo', 'createDate', 'currency', 'reportType', 'rrdId', 'giId', 'dlvPrc', 'fixTariffDateFrom', 'fixTariffDateTo', 'subjectName', 'nmId', 'brandName', 'vendorCode', 'title', 'techSize', 'sku', 'docTypeName', 'quantity', 'retailPrice', 'retailAmount', 'salePercent', 'commissionPercent', 'officeName', 'sellerOperName', 'orderDt', 'saleDt', 'rrDate', 'shkId', 'retailPriceWithDisc', 'deliveryAmount', 'returnAmount', 'deliveryService', 'giBoxTypeName', 'productDiscountForReport', 'sellerPromo', 'spp', 'kvwBase', 'kvw', 'supRatingUp', 'isKgvpV2', 'ppvzSalesCommission', 'forPay', 'ppvzReward', 'acquiringFee', 'acquiringPercent', 'paymentProcessing', 'acquiringBank', 'vw', 'vwNds', 'ppvzOfficeName', 'ppvzOfficeId', 'ppvzSupplierName', 'ppvzSupplierInn', 'declarationNumber', 'bonusTypeName', 'stickerId', 'country', 'srvDbs', 'penalty', 'additionalPayment', 'rebillLogisticCost', 'rebillLogisticOrg', 'paidStorage', 'deduction', 'paidAcceptance', 'orderId', 'kiz', 'isB2b', 'trbxId', 'installmentCofinancingAmount', 'wibesDiscountPercent', 'cashbackAmount', 'cashbackDiscount', 'cashbackCommissionChange', 'paymentSchedule', 'deliveryMethod', 'sellerPromoId', 'sellerPromoDiscount', 'loyaltyId', 'loyaltyDiscount', 'uuidPromocode', 'salePricePromocodeDiscountPrc', 'articleSubstitution', 'salePriceAffiliatedDiscountPrc', 'agencyVat', 'salePriceWholesaleDiscountPrc', 'b2bCustomerTin', 'paidWithSocialCertificate', 'warehouseLogisticsCoeff', 'orderUid', 'srid']),
        );
    }
}
