<?php

declare(strict_types=1);

/**
 * @generated Wildberries OpenAPI DTO
 */

namespace PhpSoftBox\Wildberries\Dto\Finances\Api\Supplier;

use PhpSoftBox\Wildberries\Dto\WildberriesDtoInterface;
use PhpSoftBox\Wildberries\Dto\WildberriesDtoValue;

final readonly class DetailReportItem implements WildberriesDtoInterface
{
    /**
     * @param array<array-key, mixed> $suppliercontractCode
     * @param array<string, mixed> $extra
     */
    public function __construct(
        public ?int $realizationreportId,
        public ?string $dateFrom,
        public ?string $dateTo,
        public ?string $createDt,
        public ?string $currencyName,
        public array $suppliercontractCode,
        public ?int $rrdId,
        public ?int $giId,
        public ?float $dlvPrc,
        public ?string $fixTariffDateFrom,
        public ?string $fixTariffDateTo,
        public ?string $subjectName,
        public ?int $nmId,
        public ?string $brandName,
        public ?string $saName,
        public ?string $tsName,
        public ?string $barcode,
        public ?string $docTypeName,
        public ?int $quantity,
        public ?float $retailPrice,
        public ?float $retailAmount,
        public ?int $salePercent,
        public ?float $commissionPercent,
        public ?string $officeName,
        public ?string $supplierOperName,
        public ?string $orderDt,
        public ?string $saleDt,
        public ?string $rrDt,
        public ?int $shkId,
        public ?float $retailPriceWithdiscRub,
        public ?int $deliveryAmount,
        public ?int $returnAmount,
        public ?float $deliveryRub,
        public ?string $giBoxTypeName,
        public ?float $productDiscountForReport,
        public ?float $supplierPromo,
        public ?float $ppvzSppPrc,
        public ?float $ppvzKvwPrcBase,
        public ?float $ppvzKvwPrc,
        public ?float $supRatingPrcUp,
        public ?float $isKgvpV2,
        public ?float $ppvzSalesCommission,
        public ?float $ppvzForPay,
        public ?float $ppvzReward,
        public ?float $acquiringFee,
        public ?float $acquiringPercent,
        public ?string $paymentProcessing,
        public ?string $acquiringBank,
        public ?float $ppvzVw,
        public ?float $ppvzVwNds,
        public ?string $ppvzOfficeName,
        public ?int $ppvzOfficeId,
        public ?int $ppvzSupplierId,
        public ?string $ppvzSupplierName,
        public ?string $ppvzInn,
        public ?string $declarationNumber,
        public ?string $bonusTypeName,
        public ?string $stickerId,
        public ?string $siteCountry,
        public ?bool $srvDbs,
        public ?float $penalty,
        public ?float $additionalPayment,
        public ?float $rebillLogisticCost,
        public ?string $rebillLogisticOrg,
        public ?float $storageFee,
        public ?float $deduction,
        public ?float $acceptance,
        public ?int $assemblyId,
        public ?string $kiz,
        public ?string $srid,
        public ?int $reportType,
        public ?bool $isLegalEntity,
        public ?string $trbxId,
        public ?float $installmentCofinancingAmount,
        public ?float $wibesWbDiscountPercent,
        public ?float $cashbackAmount,
        public ?float $cashbackDiscount,
        public ?float $cashbackCommissionChange,
        public ?string $orderUid,
        public ?float $paymentSchedule,
        public ?string $deliveryMethod,
        public ?int $sellerPromoId,
        public ?float $sellerPromoDiscount,
        public ?int $loyaltyId,
        public ?float $loyaltyDiscount,
        public ?string $uuidPromocode,
        public ?float $salePricePromocodeDiscountPrc,
        public ?string $articleSubstitution,
        public ?float $salePriceAffiliatedDiscountPrc,
        public ?float $agencyVat,
        public ?float $salePriceWholesaleDiscountPrc,
        public array $extra = [],
    ) {
    }

    public static function fromArray(array $payload): static
    {
        return new self(
            realizationreportId: WildberriesDtoValue::int($payload['realizationreport_id'] ?? null),
            dateFrom: WildberriesDtoValue::string($payload['date_from'] ?? null),
            dateTo: WildberriesDtoValue::string($payload['date_to'] ?? null),
            createDt: WildberriesDtoValue::string($payload['create_dt'] ?? null),
            currencyName: WildberriesDtoValue::string($payload['currency_name'] ?? null),
            suppliercontractCode: WildberriesDtoValue::array($payload['suppliercontract_code'] ?? null),
            rrdId: WildberriesDtoValue::int($payload['rrd_id'] ?? null),
            giId: WildberriesDtoValue::int($payload['gi_id'] ?? null),
            dlvPrc: WildberriesDtoValue::float($payload['dlv_prc'] ?? null),
            fixTariffDateFrom: WildberriesDtoValue::string($payload['fix_tariff_date_from'] ?? null),
            fixTariffDateTo: WildberriesDtoValue::string($payload['fix_tariff_date_to'] ?? null),
            subjectName: WildberriesDtoValue::string($payload['subject_name'] ?? null),
            nmId: WildberriesDtoValue::int($payload['nm_id'] ?? null),
            brandName: WildberriesDtoValue::string($payload['brand_name'] ?? null),
            saName: WildberriesDtoValue::string($payload['sa_name'] ?? null),
            tsName: WildberriesDtoValue::string($payload['ts_name'] ?? null),
            barcode: WildberriesDtoValue::string($payload['barcode'] ?? null),
            docTypeName: WildberriesDtoValue::string($payload['doc_type_name'] ?? null),
            quantity: WildberriesDtoValue::int($payload['quantity'] ?? null),
            retailPrice: WildberriesDtoValue::float($payload['retail_price'] ?? null),
            retailAmount: WildberriesDtoValue::float($payload['retail_amount'] ?? null),
            salePercent: WildberriesDtoValue::int($payload['sale_percent'] ?? null),
            commissionPercent: WildberriesDtoValue::float($payload['commission_percent'] ?? null),
            officeName: WildberriesDtoValue::string($payload['office_name'] ?? null),
            supplierOperName: WildberriesDtoValue::string($payload['supplier_oper_name'] ?? null),
            orderDt: WildberriesDtoValue::string($payload['order_dt'] ?? null),
            saleDt: WildberriesDtoValue::string($payload['sale_dt'] ?? null),
            rrDt: WildberriesDtoValue::string($payload['rr_dt'] ?? null),
            shkId: WildberriesDtoValue::int($payload['shk_id'] ?? null),
            retailPriceWithdiscRub: WildberriesDtoValue::float($payload['retail_price_withdisc_rub'] ?? null),
            deliveryAmount: WildberriesDtoValue::int($payload['delivery_amount'] ?? null),
            returnAmount: WildberriesDtoValue::int($payload['return_amount'] ?? null),
            deliveryRub: WildberriesDtoValue::float($payload['delivery_rub'] ?? null),
            giBoxTypeName: WildberriesDtoValue::string($payload['gi_box_type_name'] ?? null),
            productDiscountForReport: WildberriesDtoValue::float($payload['product_discount_for_report'] ?? null),
            supplierPromo: WildberriesDtoValue::float($payload['supplier_promo'] ?? null),
            ppvzSppPrc: WildberriesDtoValue::float($payload['ppvz_spp_prc'] ?? null),
            ppvzKvwPrcBase: WildberriesDtoValue::float($payload['ppvz_kvw_prc_base'] ?? null),
            ppvzKvwPrc: WildberriesDtoValue::float($payload['ppvz_kvw_prc'] ?? null),
            supRatingPrcUp: WildberriesDtoValue::float($payload['sup_rating_prc_up'] ?? null),
            isKgvpV2: WildberriesDtoValue::float($payload['is_kgvp_v2'] ?? null),
            ppvzSalesCommission: WildberriesDtoValue::float($payload['ppvz_sales_commission'] ?? null),
            ppvzForPay: WildberriesDtoValue::float($payload['ppvz_for_pay'] ?? null),
            ppvzReward: WildberriesDtoValue::float($payload['ppvz_reward'] ?? null),
            acquiringFee: WildberriesDtoValue::float($payload['acquiring_fee'] ?? null),
            acquiringPercent: WildberriesDtoValue::float($payload['acquiring_percent'] ?? null),
            paymentProcessing: WildberriesDtoValue::string($payload['payment_processing'] ?? null),
            acquiringBank: WildberriesDtoValue::string($payload['acquiring_bank'] ?? null),
            ppvzVw: WildberriesDtoValue::float($payload['ppvz_vw'] ?? null),
            ppvzVwNds: WildberriesDtoValue::float($payload['ppvz_vw_nds'] ?? null),
            ppvzOfficeName: WildberriesDtoValue::string($payload['ppvz_office_name'] ?? null),
            ppvzOfficeId: WildberriesDtoValue::int($payload['ppvz_office_id'] ?? null),
            ppvzSupplierId: WildberriesDtoValue::int($payload['ppvz_supplier_id'] ?? null),
            ppvzSupplierName: WildberriesDtoValue::string($payload['ppvz_supplier_name'] ?? null),
            ppvzInn: WildberriesDtoValue::string($payload['ppvz_inn'] ?? null),
            declarationNumber: WildberriesDtoValue::string($payload['declaration_number'] ?? null),
            bonusTypeName: WildberriesDtoValue::string($payload['bonus_type_name'] ?? null),
            stickerId: WildberriesDtoValue::string($payload['sticker_id'] ?? null),
            siteCountry: WildberriesDtoValue::string($payload['site_country'] ?? null),
            srvDbs: WildberriesDtoValue::bool($payload['srv_dbs'] ?? null),
            penalty: WildberriesDtoValue::float($payload['penalty'] ?? null),
            additionalPayment: WildberriesDtoValue::float($payload['additional_payment'] ?? null),
            rebillLogisticCost: WildberriesDtoValue::float($payload['rebill_logistic_cost'] ?? null),
            rebillLogisticOrg: WildberriesDtoValue::string($payload['rebill_logistic_org'] ?? null),
            storageFee: WildberriesDtoValue::float($payload['storage_fee'] ?? null),
            deduction: WildberriesDtoValue::float($payload['deduction'] ?? null),
            acceptance: WildberriesDtoValue::float($payload['acceptance'] ?? null),
            assemblyId: WildberriesDtoValue::int($payload['assembly_id'] ?? null),
            kiz: WildberriesDtoValue::string($payload['kiz'] ?? null),
            srid: WildberriesDtoValue::string($payload['srid'] ?? null),
            reportType: WildberriesDtoValue::int($payload['report_type'] ?? null),
            isLegalEntity: WildberriesDtoValue::bool($payload['is_legal_entity'] ?? null),
            trbxId: WildberriesDtoValue::string($payload['trbx_id'] ?? null),
            installmentCofinancingAmount: WildberriesDtoValue::float($payload['installment_cofinancing_amount'] ?? null),
            wibesWbDiscountPercent: WildberriesDtoValue::float($payload['wibes_wb_discount_percent'] ?? null),
            cashbackAmount: WildberriesDtoValue::float($payload['cashback_amount'] ?? null),
            cashbackDiscount: WildberriesDtoValue::float($payload['cashback_discount'] ?? null),
            cashbackCommissionChange: WildberriesDtoValue::float($payload['cashback_commission_change'] ?? null),
            orderUid: WildberriesDtoValue::string($payload['order_uid'] ?? null),
            paymentSchedule: WildberriesDtoValue::float($payload['payment_schedule'] ?? null),
            deliveryMethod: WildberriesDtoValue::string($payload['delivery_method'] ?? null),
            sellerPromoId: WildberriesDtoValue::int($payload['seller_promo_id'] ?? null),
            sellerPromoDiscount: WildberriesDtoValue::float($payload['seller_promo_discount'] ?? null),
            loyaltyId: WildberriesDtoValue::int($payload['loyalty_id'] ?? null),
            loyaltyDiscount: WildberriesDtoValue::float($payload['loyalty_discount'] ?? null),
            uuidPromocode: WildberriesDtoValue::string($payload['uuid_promocode'] ?? null),
            salePricePromocodeDiscountPrc: WildberriesDtoValue::float($payload['sale_price_promocode_discount_prc'] ?? null),
            articleSubstitution: WildberriesDtoValue::string($payload['article_substitution'] ?? null),
            salePriceAffiliatedDiscountPrc: WildberriesDtoValue::float($payload['sale_price_affiliated_discount_prc'] ?? null),
            agencyVat: WildberriesDtoValue::float($payload['agency_vat'] ?? null),
            salePriceWholesaleDiscountPrc: WildberriesDtoValue::float($payload['sale_price_wholesale_discount_prc'] ?? null),
            extra: WildberriesDtoValue::extra($payload, ['realizationreport_id', 'date_from', 'date_to', 'create_dt', 'currency_name', 'suppliercontract_code', 'rrd_id', 'gi_id', 'dlv_prc', 'fix_tariff_date_from', 'fix_tariff_date_to', 'subject_name', 'nm_id', 'brand_name', 'sa_name', 'ts_name', 'barcode', 'doc_type_name', 'quantity', 'retail_price', 'retail_amount', 'sale_percent', 'commission_percent', 'office_name', 'supplier_oper_name', 'order_dt', 'sale_dt', 'rr_dt', 'shk_id', 'retail_price_withdisc_rub', 'delivery_amount', 'return_amount', 'delivery_rub', 'gi_box_type_name', 'product_discount_for_report', 'supplier_promo', 'ppvz_spp_prc', 'ppvz_kvw_prc_base', 'ppvz_kvw_prc', 'sup_rating_prc_up', 'is_kgvp_v2', 'ppvz_sales_commission', 'ppvz_for_pay', 'ppvz_reward', 'acquiring_fee', 'acquiring_percent', 'payment_processing', 'acquiring_bank', 'ppvz_vw', 'ppvz_vw_nds', 'ppvz_office_name', 'ppvz_office_id', 'ppvz_supplier_id', 'ppvz_supplier_name', 'ppvz_inn', 'declaration_number', 'bonus_type_name', 'sticker_id', 'site_country', 'srv_dbs', 'penalty', 'additional_payment', 'rebill_logistic_cost', 'rebill_logistic_org', 'storage_fee', 'deduction', 'acceptance', 'assembly_id', 'kiz', 'srid', 'report_type', 'is_legal_entity', 'trbx_id', 'installment_cofinancing_amount', 'wibes_wb_discount_percent', 'cashback_amount', 'cashback_discount', 'cashback_commission_change', 'order_uid', 'payment_schedule', 'delivery_method', 'seller_promo_id', 'seller_promo_discount', 'loyalty_id', 'loyalty_discount', 'uuid_promocode', 'sale_price_promocode_discount_prc', 'article_substitution', 'sale_price_affiliated_discount_prc', 'agency_vat', 'sale_price_wholesale_discount_prc']),
        );
    }
}
